[package]
edition = "2021"
name = "abi-checker"
version = "0.1.0"


[features]
default = []
# Doesn't actually work yet...
parallel = ["rayon"]


[dependencies]
built = "0.5.1"
cc = { version = "1.0.73", git = "https://github.com/Gankra/cc-rs" }
clap = { version = "3.1.6", features = ["cargo", "wrap_help"] }
libloading = "0.7.3"
linked-hash-map = { version = "0.5.6", features = ["serde", "serde_impl"] }
log = "0.4.14"
rayon = { version = "1.5.3", optional = true }
ron = "0.7.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.83"
simplelog = "0.11.2"
thiserror = "1.0.30"



[build-dependencies]
built = "*"
